import { ArrowRight, Check, MapPin, MonitorSmartphone, Search, Workflow, Compass, Wrench, Waves, Trees, Building2 } from 'lucide-react';

function Logo({ light = true }: { light?: boolean }) {
  return <a href="#home" className={`brand ${light ? '' : 'brand-dark'}`} aria-label="MidCoast Web Co. home"><img src={light ? '/mwc-logo-light.svg' : '/mwc-logo-dark.svg'} alt="MidCoast Web Co. — Websites, SEO, Automation" /></a>;
}

const services = [
  { icon: MonitorSmartphone, number:'01', title:'Websites', text:'Fast, polished websites that earn trust, explain your value and turn local visitors into genuine enquiries.', points:['Custom responsive design','Clear lead-generation paths','Hosting and ongoing care'] },
  { icon: Search, number:'02', title:'Local SEO', text:'Practical search foundations that help the right people find your business when they need it.', points:['Local search structure','On-page SEO foundations','Measurement that makes sense'] },
  { icon: Workflow, number:'03', title:'Automation', text:'Simple connected systems that reduce repetitive admin and keep opportunities moving.', points:['Lead and enquiry workflows','Smart forms and follow-up','Room to grow into software'] },
];

export default function Home() {
  return <main id="home">
    <header className="site-header"><div className="container nav-wrap"><Logo/><nav aria-label="Main navigation"><a href="#services">Services</a><a href="#about">About</a><a href="#contact">Contact</a></nav><a className="button button-small" href="#contact">Start a project <ArrowRight size={15}/></a></div></header>

    <section className="hero"><div className="hero-shade"/><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><MapPin size={15}/> Proudly MidCoast</p><h1>Websites that<br/>grow <em>your business.</em></h1><p className="hero-lead">Web Design. SEO. Automation.<br/>Built for the MidCoast.</p><div className="hero-actions"><a className="button" href="#contact">Let&apos;s talk <ArrowRight size={18}/></a></div><div className="trust-row"><span><Check/> Clear, fixed scope</span><span><Check/> Built for mobile</span><span><Check/> Local support</span></div></div></div><div className="service-line"><span>Websites</span><i/><span>SEO</span><i/><span>Automation</span></div></section>

    <section id="services" className="section intro-section"><div className="container"><div className="intro-grid"><p className="section-kicker">What we do</p><div><h2>A sharper digital presence.<br/><span>Less digital busywork.</span></h2><p>We help good local businesses look established, get found and run more smoothly online.</p></div></div><div className="service-cards">{services.map(({icon:Icon,...s})=><article className="service-card" key={s.title}><div className="card-top"><Icon/><span>{s.number}</span></div><h3>{s.title}</h3><p>{s.text}</p><ul>{s.points.map(p=><li key={p}><Check/>{p}</li>)}</ul></article>)}</div></div></section>

    <section className="audience section"><div className="container audience-grid"><div><p className="section-kicker">Built around your business</p><h2>Local knowledge.<br/><span>Commercial thinking.</span></h2><p>We build for businesses whose reputation matters: straightforward communication, quality work and no time for digital nonsense.</p><a href="#contact" className="text-link dark-link">Tell us what you need <ArrowRight size={16}/></a></div><div className="industry-list"><span><Wrench/> Tradies & services</span><span><Building2/> Builders & property</span><span><Trees/> Landscapers & outdoors</span><span><Waves/> Marine & tourism</span><span><Compass/> Regional operators</span></div></div></section>

    <section id="about" className="section about-section"><div className="container about-grid"><div className="about-mark"><div className="about-logo-lockup"><Logo/><p>WEBSITES <i/> SEO <i/> AUTOMATION</p></div></div><div><p className="section-kicker">About MWC</p><h2>Your local technology partner, not another anonymous agency.</h2><p>MidCoast Web Co. exists to give owner-operated businesses access to thoughtful design and modern technology without the jargon, handballing or city-agency overhead.</p><p>We start with websites and search — then stay ready to help with the automation and software opportunities that appear as your business grows.</p><div className="about-values"><span><b>Clear</b> Straight answers and scope</span><span><b>Local</b> Mid North Coast perspective</span><span><b>Useful</b> Technology with a job to do</span></div></div></div></section>

    <section className="process section"><div className="container"><p className="section-kicker">How it works</p><div className="process-grid"><article><b>01</b><h3>Tell us about the business</h3><p>A practical conversation about where you are, what&apos;s not working and what success looks like.</p></article><article><b>02</b><h3>Get a clear direction</h3><p>We shape the scope, structure and visual approach before the build gathers momentum.</p></article><article><b>03</b><h3>Launch with confidence</h3><p>Your site is refined for mobile, search and enquiries, with a straightforward path for ongoing care.</p></article></div></div></section>

    <section id="contact" className="contact-section"><div className="container contact-grid"><div><p className="eyebrow">Start a conversation</p><h2>Ready for a website that feels like your business has arrived?</h2><p>Tell us what you do, where you operate and what you want the website to achieve. We&apos;ll come back with a clear next step.</p></div><div className="contact-card"><p className="contact-label">New business enquiries</p><a className="email-link" href="mailto:hello@midcoastweb.com.au?subject=Website%20project%20enquiry">hello@midcoastweb.com.au <ArrowRight/></a><p className="replace-note">Launch check: confirm this inbox is active before public domain cutover.</p><div className="contact-divider"/><p><MapPin/> Serving the Mid North Coast and working with great regional businesses across Australia.</p></div></div></section>

    <footer><div className="container footer-main"><Logo/><div className="footer-links"><a href="#services">Services</a><a href="#about">About</a><a href="#contact">Contact</a></div><a className="top-link" href="#home">Back to top ↑</a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} MidCoast Web Co.</span><span>Websites • SEO • Automation</span><span>midcoastweb.com.au</span></div></footer>
  </main>;
}

