import { ArrowRight, Check, MapPin, MonitorSmartphone, Search, Workflow, Compass, Wrench, Waves, Trees, Building2 } from 'lucide-react';

function Logo({ light = true }: { light?: boolean }) {
  return <a href="/" className={`brand ${light ? '' : 'brand-dark'}`} aria-label="MidCoast Web Co. home"><img src={light ? '/mwc-logo-light.svg' : '/mwc-logo-dark.svg'} alt="MidCoast Web Co. — Websites, SEO, Automation" /></a>;
}

const services = [
  { icon: MonitorSmartphone, number:'01', title:'Web Design', text:'Websites for local businesses that need to look sharp, explain what they do quickly and make it easy for customers to get in touch.', points:['Custom responsive design','Clear enquiry paths','Hosting and ongoing care'] },
  { icon: Search, number:'02', title:'Local SEO', text:'We sort out the practical things that help Google understand your business — services, locations, page structure and the signals that matter locally.', points:['Local search structure','On-page SEO foundations','Useful reporting'] },
  { icon: Workflow, number:'03', title:'Automation', text:'When admin starts repeating itself, we look for sensible ways to connect the pieces and cut down the manual work.', points:['Lead and enquiry workflows','Smart forms and follow-up','Room to grow into software'] },
];

const industries = [
  { icon: Wrench, number: '01', title: 'Trades & services', text: 'Clear service areas, straightforward quotes and an easy way for local customers to get in touch.' },
  { icon: Building2, number: '02', title: 'Builders & property', text: 'Project-led websites that show the quality of your work and build confidence before the first call.' },
  { icon: Trees, number: '03', title: 'Landscapers & outdoors', text: 'Visual, practical sites made to showcase finished work and turn local interest into enquiries.' },
  { icon: Waves, number: '04', title: 'Marine & tourism', text: 'Mobile-friendly websites that help visitors find, understand and book local experiences.' },
  { icon: Compass, number: '05', title: 'Regional operators', text: 'A capable online presence for businesses covering wide service areas, multiple towns or specialist markets.' },
];

export default function Home() {
  return <main id="home">
    <header className="site-header"><div className="container nav-wrap"><Logo/><nav aria-label="Main navigation"><a href="#services">Services</a><a href="#locations">Areas</a><a href="/local-seo/">Local SEO</a><a href="/website-care/">Website Care</a><a href="#about">About</a></nav><a className="button button-small" href="#contact">Start a project <ArrowRight size={15}/></a></div></header>

    <section className="hero"><div className="hero-shade"/><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><MapPin size={15}/> Forster • Tuncurry • Mid North Coast</p><h1>Web Design for Forster &amp; the <em>Mid North Coast.</em></h1><p className="hero-lead">Websites. SEO. Automation.<br/>Built for local business growth.</p><div className="hero-actions"><a className="button" href="#contact">Let&apos;s talk <ArrowRight size={18}/></a></div><div className="trust-row"><span><Check/> Clear, fixed scope</span><span><Check/> Built for mobile</span><span><Check/> Local support</span></div></div></div><div className="service-line"><span>Websites</span><i/><span>SEO</span><i/><span>Automation</span></div></section>

    <section id="services" className="section intro-section"><div className="container"><div className="intro-grid"><p className="section-kicker">What we do</p><div><h2>Useful websites and digital systems for Mid North Coast businesses.</h2><p>We build the things that help a local business look credible, get found and stay organised. Sometimes that means a new website. Sometimes it means fixing the site you already have, tightening up your Google presence, or removing a repetitive admin job.</p></div></div><div className="service-cards">{services.map(({icon:Icon,...s})=><article className="service-card" key={s.title}><div className="card-top"><Icon/><span>{s.number}</span></div><h3>{s.title}</h3><p>{s.text}</p><ul>{s.points.map(p=><li key={p}><Check/>{p}</li>)}</ul></article>)}</div></div></section>

    <section id="locations" className="audience section"><div className="container audience-grid"><div><p className="section-kicker">Local web design</p><h2>Based on the MidCoast.<br/><span>Built for regional business.</span></h2><p>We work with businesses in Forster, Tuncurry, Taree and around the Mid North Coast. The aim is simple: make the website feel like the business behind it, not like something pulled off a template shelf.</p><p>That means getting the practical details right — the services you actually sell, the areas you actually cover, the work you are proud of, and the easiest way for a customer to contact you.</p><div className="location-links"><a href="/web-design-forster/" className="text-link dark-link">Web design in Forster <ArrowRight size={16}/></a><a href="/web-design-tuncurry/" className="text-link dark-link">Web design in Tuncurry <ArrowRight size={16}/></a><a href="/web-design-taree/" className="text-link dark-link">Web design in Taree <ArrowRight size={16}/></a></div></div><div className="industry-panel" aria-label="Industries we work with"><p className="industry-panel-label">Who we work with</p><div className="industry-list">{industries.map(({ icon: Icon, ...industry }) => <article className="industry-item" key={industry.title}><div className="industry-icon" aria-hidden="true"><Icon/></div><div className="industry-copy"><span className="industry-number">{industry.number}</span><h3>{industry.title}</h3><p>{industry.text}</p></div></article>)}</div></div></div></section>

    <section id="about" className="section about-section"><div className="container about-grid"><div className="about-mark"><div className="about-logo-lockup"><Logo/><p>WEBSITES <i/> SEO <i/> AUTOMATION</p></div></div><div><p className="section-kicker">About MWC</p><h2>A small MidCoast web company that keeps things practical.</h2><p>MidCoast Web Co. was started to give local owner-operated businesses another option besides doing everything themselves or handing the job to a large agency they rarely speak to.</p><p>We keep the process direct. If something can be explained simply, we explain it simply. If a feature does not help the customer or the business, it does not need to be there. And when a website is finished, we can keep looking after it instead of disappearing after launch.</p><div className="about-values"><span><b>Clear</b> Straight answers and scope</span><span><b>Local</b> Mid North Coast perspective</span><span><b>Useful</b> Technology with a job to do</span></div></div></div></section>

    <section className="process section"><div className="container"><p className="section-kicker">How it works</p><div className="process-grid"><article><b>01</b><h3>Show us where you are now</h3><p>Send through the current site, or tell us what you need if you are starting from scratch. We look at the business before we talk about design.</p></article><article><b>02</b><h3>Agree on the job</h3><p>We set the scope, pages, priorities and direction before the build gets underway, so there are fewer surprises later.</p></article><article><b>03</b><h3>Launch it properly</h3><p>We check mobile, search basics and enquiry paths, then get the site live with a clear plan for what happens next.</p></article></div></div></section>

    <section id="contact" className="contact-section"><div className="container contact-grid"><div><p className="eyebrow">Start a conversation</p><h2>If your current website is letting the business down, send it through.</h2><p>Tell us what you do, where you work and what is frustrating you about the current setup. We&apos;ll take a look and tell you what we would fix first.</p></div><div className="contact-card"><p className="contact-label">New business enquiries</p><a className="email-link" href="mailto:hello@midcoastweb.com.au?subject=Website%20project%20enquiry">hello@midcoastweb.com.au <ArrowRight/></a><div className="contact-divider"/><p><MapPin/> Serving Forster, Tuncurry and the Mid North Coast, and working with regional businesses elsewhere in Australia when the fit makes sense.</p></div></div></section>

    <footer><div className="container footer-main"><Logo/><div className="footer-links"><a href="/web-design-forster/">Forster</a><a href="/web-design-tuncurry/">Tuncurry</a><a href="/web-design-taree/">Taree</a><a href="/local-seo/">Local SEO</a><a href="/website-care/">Website Care</a><a href="#contact">Contact</a></div><a className="top-link" href="#home">Back to top ↑</a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} MidCoast Web Co.</span><span>Websites • SEO • Automation</span><span>midcoastweb.com.au</span></div></footer>
  </main>;
}
