import { ArrowRight, Check, MapPin, MonitorSmartphone, Search, Workflow, Compass, Wrench, Waves, Trees, Building2 } from 'lucide-react';

function Logo({ light = true }: { light?: boolean }) {
  return <a href="/" className={`brand ${light ? '' : 'brand-dark'}`} aria-label="MidCoast Web Co. home"><img src={light ? '/mwc-logo-light.svg' : '/mwc-logo-dark.svg'} alt="MidCoast Web Co. — Websites, SEO, Automation" /></a>;
}

const services = [
  { icon: MonitorSmartphone, number:'01', title:'Web Design', text:'Fast, polished websites for Forster, Tuncurry and Mid North Coast businesses that earn trust, explain your value and turn local visitors into genuine enquiries.', points:['Custom responsive design','Clear lead-generation paths','Hosting and ongoing care'] },
  { icon: Search, number:'02', title:'Local SEO', text:'Practical local SEO foundations that help the right people find your business in Google when they need it.', points:['Local search structure','On-page SEO foundations','Measurement that makes sense'] },
  { icon: Workflow, number:'03', title:'Automation', text:'Simple connected systems that reduce repetitive admin and keep opportunities moving.', points:['Lead and enquiry workflows','Smart forms and follow-up','Room to grow into software'] },
];

export default function Home() {
  return <main id="home">
    <header className="site-header"><div className="container nav-wrap"><Logo/><nav aria-label="Main navigation"><a href="#services">Services</a><a href="#locations">Areas</a><a href="/local-seo/">Local SEO</a><a href="/website-care/">Website Care</a><a href="#about">About</a></nav><a className="button button-small" href="#contact">Start a project <ArrowRight size={15}/></a></div></header>

    <section className="hero"><div className="hero-shade"/><div className="container hero-grid"><div className="hero-copy"><p className="eyebrow"><MapPin size={15}/> Forster • Tuncurry • Mid North Coast</p><h1>Web Design for Forster &amp; the <em>Mid North Coast.</em></h1><p className="hero-lead">Websites. SEO. Automation.<br/>Built for local business growth.</p><div className="hero-actions"><a className="button" href="#contact">Let&apos;s talk <ArrowRight size={18}/></a></div><div className="trust-row"><span><Check/> Clear, fixed scope</span><span><Check/> Built for mobile</span><span><Check/> Local support</span></div></div></div><div className="service-line"><span>Websites</span><i/><span>SEO</span><i/><span>Automation</span></div></section>

    <section id="services" className="section intro-section"><div className="container"><div className="intro-grid"><p className="section-kicker">What we do</p><div><h2>Websites, local SEO and automation for Mid North Coast businesses.</h2><p>We help good local businesses look established, get found and run more smoothly online. Explore our <a href="/local-seo/">local SEO services</a> and <a href="/website-care/">website care plans</a>.</p></div></div><div className="service-cards">{services.map(({icon:Icon,...s})=><article className="service-card" key={s.title}><div className="card-top"><Icon/><span>{s.number}</span></div><h3>{s.title}</h3><p>{s.text}</p><ul>{s.points.map(p=><li key={p}><Check/>{p}</li>)}</ul></article>)}</div></div></section>

    <section id="locations" className="audience section"><div className="container audience-grid"><div><p className="section-kicker">Local web design</p><h2>Based on the MidCoast.<br/><span>Built for regional business.</span></h2><p>MidCoast Web Co. provides web design, local SEO and practical automation for businesses in Forster, Tuncurry, Taree, Nabiac, Hallidays Point, Pacific Palms and across the Mid North Coast NSW.</p><p>Whether you need a new website, a redesign that generates more enquiries, stronger Google visibility or a simpler way to handle leads, we build around the way your business actually operates.</p><div className="location-links"><a href="/web-design-forster/" className="text-link dark-link">Web design in Forster <ArrowRight size={16}/></a><a href="/web-design-tuncurry/" className="text-link dark-link">Web design in Tuncurry <ArrowRight size={16}/></a><a href="/web-design-taree/" className="text-link dark-link">Web design in Taree <ArrowRight size={16}/></a></div></div><div className="industry-list"><span><Wrench/> Tradies & services</span><span><Building2/> Builders & property</span><span><Trees/> Landscapers & outdoors</span><span><Waves/> Marine & tourism</span><span><Compass/> Regional operators</span></div></div></section>

    <section id="about" className="section about-section"><div className="container about-grid"><div className="about-mark"><div className="about-logo-lockup"><Logo/><p>WEBSITES <i/> SEO <i/> AUTOMATION</p></div></div><div><p className="section-kicker">About MWC</p><h2>Your local technology partner, not another anonymous agency.</h2><p>MidCoast Web Co. exists to give owner-operated businesses access to thoughtful web design and modern technology without the jargon, handballing or city-agency overhead.</p><p>We start with websites and search — then stay ready to help with the automation and software opportunities that appear as your business grows.</p><div className="about-values"><span><b>Clear</b> Straight answers and scope</span><span><b>Local</b> Mid North Coast perspective</span><span><b>Useful</b> Technology with a job to do</span></div></div></div></section>

    <section className="process section"><div className="container"><p className="section-kicker">How it works</p><div className="process-grid"><article><b>01</b><h3>Tell us about the business</h3><p>A practical conversation about where you are, what&apos;s not working and what success looks like.</p></article><article><b>02</b><h3>Get a clear direction</h3><p>We shape the scope, structure and visual approach before the build gathers momentum.</p></article><article><b>03</b><h3>Launch with confidence</h3><p>Your site is refined for mobile, search and enquiries, with a straightforward path for ongoing care.</p></article></div></div></section>

    <section id="contact" className="contact-section"><div className="container contact-grid"><div><p className="eyebrow">Start a conversation</p><h2>Ready for a website that feels like your business has arrived?</h2><p>Tell us what you do, where you operate and what you want the website to achieve. We&apos;ll come back with a clear next step.</p></div><div className="contact-card"><p className="contact-label">New business enquiries</p><a className="email-link" href="mailto:hello@midcoastweb.com.au?subject=Website%20project%20enquiry">hello@midcoastweb.com.au <ArrowRight/></a><div className="contact-divider"/><p><MapPin/> Serving Forster, Tuncurry and the Mid North Coast, and working with great regional businesses across Australia.</p></div></div></section>

    <footer><div className="container footer-main"><Logo/><div className="footer-links"><a href="/web-design-forster/">Forster</a><a href="/web-design-tuncurry/">Tuncurry</a><a href="/web-design-taree/">Taree</a><a href="/local-seo/">Local SEO</a><a href="/website-care/">Website Care</a><a href="#contact">Contact</a></div><a className="top-link" href="#home">Back to top ↑</a></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} MidCoast Web Co.</span><span>Websites • SEO • Automation</span><span>midcoastweb.com.au</span></div></footer>
  </main>;
}
